### ISSUE TITLE
Testing pull request

### ISSUE THREAD

**Issue by gusDuarte** [activitycentral/statistics-consolidation#2]
Miguel,

I'm trying your pull request, after run "make" following error was raised:

python: can't open file '../.venv/bin/coverage': [Errno 2] No such file or directory
make: **\* [.coverage] Error 2

I'm missing install something else ?

**Comment by migonzalvar** [comment]
This Makefile is for testing purposes and requires `coverage` package. It also supposes you're in a virtualenv with a path relative to the project. I'm going to send a patch to avoid check this requirements.

**Comment by migonzalvar** [comment]
See https://github.com/migonzalvar/statistics-consolidation/commit/1208944595244da0ef5380456d19fe30c6de9ab3
